### ISSUE TITLE
E/take screenshot(18046): take screenshot error!

### ISSUE THREAD

**Issue by zjm1126** [HasanToufiqAhamed/device_screenshot#7]
this is error when run example .  so how to fix this.

**Comment by HasanToufiqApsis** [comment]
i will working on it. please mention your android api level please @zjm1126

**Comment by HasanToufiqAhamed** [comment]
i will be working on it. please mention your Android API level please @zjm1126

**Comment by HasanToufiqAhamed** [comment]
To capture screenshot you need to request Media Projection Service first
Do this first DeviceScreenshot.instance.requestMediaProjection();

**Comment by HasanToufiqAhamed** [comment]
To capture screenshot you need to request Media Projection Service first
Do this first DeviceScreenshot.instance.requestMediaProjection();
